development:
  duplicate_user_password: Tom168!!
  twilio_user: twilio
  twilio_password: tw!l!0M0nkey
  twilio_auth_token: a8f05b5fe38f466044099f22e5dc6767
  ops_user: opsmonkey
  ops_password: RpF8!47h14
  ops_auth_token: 3d73053pd727g6jxkwy5b476373l352l
  google_api_key: AIzaSyDTkcTT2QvlNasFR4bsp5fTT91KhhIvFRk
  monkey_notifications_url: 'https://alertengine-development.malauzai.com'
  mz_firebase_server: 'https://alertengine-development.malauzai.com:5100'
  mz_location_server: 'http://alertengine-development.malauzai.com:5400'
  m1_webster_bank_adapter_server: 'http://alertengine-development.malauzai.com:5500'
  m1_webster_bank_adapter_server_dev: 'http://alertengine-development.malauzai.com:5600'
  m1_ultradata_adapter_server: 'http://alertengine-development.malauzai.com:5700'
  m1_xpress_deposit_adapter_server: 'http://alertengine-development.malauzai.com:5800'
  m1_alpha_omega_adapter_v1: 'http://alertengine-development.malauzai.com:6850/v1'

test:
  duplicate_user_password: Tom168!!
  twilio_user: twilio
  twilio_password: tw!l!0M0nkey
  twilio_auth_token: a8f05b5fe38f466044099f22e5dc6767
  ops_user: opsmonkey
  ops_password: RpF8!47h14
  ops_auth_token: 3d73053pd727g6jxkwy5b476373l352l
  google_api_key: AIzaSyDTkcTT2QvlNasFR4bsp5fTT91KhhIvFRk
  monkey_notifications_url: 'https://alertengine-development.malauzai.com'
  mz_firebase_server: 'https://alertengine-development.malauzai.com:5100'
  mz_location_server: 'http://alertengine-development.malauzai.com:5400'
  m1_webster_bank_adapter_server: 'http://alertengine-development.malauzai.com:5500'
  m1_webster_bank_adapter_server_dev: 'http://alertengine-development.malauzai.com:5600'
  m1_ultradata_adapter_server: 'http://alertengine-development.malauzai.com:5700'
  m1_xpress_deposit_adapter_server: 'http://alertengine-development.malauzai.com:5800'
  m1_locations_server: 'http://alertengine-development.malauzai.com:5310'
  m1_phoenix_adapter_horicon_test_server: 'http://alertengine-development.malauzai.com:6200'
  m1_phoenix_adapter_horicon_live_server: 'http://alertengine-development.malauzai.com:6210'
  m1_webster_alerts_adapter_server: 'http://alertengine-development.malauzai.com:5900'
  m1_symantec_adapter: 'https://m1_symantec_adapter_server.malauzai.com'
  m1_summit_adapter_server: 'http://rsdevelopment.malauzai.com:6930'
  m1_ipay_adapter_server: 'http://alertengine-development.malauzai.com:5810'
  m1_horizon_adapter: 'http://test.malauzai.com:5850'
  m1_xp2_adapter: 'http://test.malauzai.com:6830'
  m1_identifi_adapter: 'http://test.malauzai.com:6950'

production:
  duplicate_user_password: Tom168!!
  twilio_user: twilio
  twilio_password: tw!l!0M0nkey
  twilio_auth_token: a8f05b5fe38f466044099f22e5dc6767
  ops_user: opsmonkey
  ops_password: RpF8!47h14
  ops_auth_token: 3d73053pd727g6jxkwy5b476373l352l
  yandex_translate_key: trnsl.1.1.20161219T035806Z.85c2aa7048509515.09429df7862e3fd01eca2e318bea2776d3cfed38
  google_api_key: AIzaSyDTkcTT2QvlNasFR4bsp5fTT91KhhIvFRk
  monkey_notifications_url: 'https://alertengine-development.malauzai.com'
  mz_location_server: 'http://localhost:5300'
  m1_locations_server: 'http://alertengine.malauzai.com:6030' # Pointing this to prod for the time being, since firewall rules are preventing dev locations app from working
  m1_ultradata_adapter_server: 'http://localhost:5700'
  m1_ultradata_adapter_live_1: 'http://localhost:5700'
  m1_iti_premier_adapter_server: 'http://localhost:5820'
  m1_xpress_deposit_adapter_server: 'http://localhost:5800'
  m1_webster_alerts_adapter_server: 'http://localhost:5900'
  m1_symantec_adapter: 'http://localhost:6300'
  m1_symxchange_adapter: 'http://localhost:6400'
  m1_phoenix_adapter_test_1_server: 'http://localhost:6200'
  m1_summit_adapter_server: 'http://localhost:6930'
  SECRET_KEY_BASE: '8aca0e61e28196a057660f259c79248c27104008240d1e093b46ea777064ec4358a7a62319f7906fb943d51814cd768471ae423550c2e859ad6a15cf1927b213'
  sami_certificate: '/etc/ssl/servercerts/sami.malauzai.com.crt'
  sami_certificate_key: '/etc/ssl/servercerts/sami.malauzai.com.key'
  m1_horizon_adapter: 'http://localhost:5850'
  INTERNAL_P2P_JWT_SECRET: 702982e68223ab919ce7af6bf93073660753e0623cdbd1c5b15ff91c914f366d
  internal_p2p_service: 'http://localhost:6820'
  m1_precision_adapter_server: 'http://localhost:6870'
  m1_cohesion_adapter_server: 'http://localhost:6600'
  statement_fetching_service: 'http://localhost:6960'
  statement_directory: '/home/mastermonkey/statement-fetching-service/statements'
  ach_uploads_directory: '/home/mastermonkey/retail_plus/ach_uploads'
  xml_processing_service: 'http://localhost:6990'
  socket_cluster_url: 'ws://localhost:8000/socketcluster/'
  m1_midwest_printing_adapter: 'http://localhost:6920'
  m1_alpha_omega_adapter_v1: 'http://localhost:6850/v1'
  savings_rewards_service: 'http://localhost:6980'
  m1_myriad_adapter_server: 'http://localhost:5860'
  m1_ims_integration_adapter_server: 'http://localhost:5830'
  m1_webster_api_adapter_server: 'http://localhost:6260'
  m1_sym_app_adapter_server: 'http://localhost:6860'
  m1_mci_adapter_server: 'http://localhost:6910'
  m1_deluxe_services_adapter_server: 'http://localhost:5840'
  m1_monotto_adapter: 'http://localhost:6940'
  m1_bottomline-oflows-sso-adapter: 'http://localhost:6700'
  m1_webster_bank_adapter_server: 'http://localhost:5500'
  m1_cubus_adapter_server: 'http://localhost:6500'
  m1_wausau_adapter: 'http://localhost:6250'
  m1_phoenix_adapter_dh25571_test_server: 'http://localhost:6230'
  m1_phoenix_adapter_test_1_server: 'http://localhost:6200'
  m1_xp2_adapter: 'http://localhost:6830'
  m1_identifi_adapter: 'http://localhost:6950'
  m1_datasafe_adapter_v1: 'http://localhost:6970/v1'
