#!/bin/sh
#load helper functions from main script
source helper_functions

message_user "Enter the full path to your SAMI repo\n\n Ex: /Users/mike.rode/Malauzai/sami"

while [ 1 ]
do
  read answer
  if [[ $answer == *"sami"* ]]; then
    sami_dir=$answer
    break
  else
    message_user "Please check that you have entered the correct path"
  fi
done

if [ ! -f "$sami_dir/config/database.yml" ]; then
  fancy_echo "Creating database.yml file"
  cp $DIR/install_files/database.yml $sami_dir/config/
fi

if [ ! -f "$sami_dir/config/app_config.yml" ]; then
  fancy_echo "Creating app_config.yml file"
  cp $DIR/install_files/app_config.yml $sami_dir/config/
fi

certs=("${sami_dir}/config/certificates/*")

while IFS= read -r filename; do 
  if containsElement "${filename}" "${certs[@]}"; then
    continue
  fi
  if [ ! -f "$sami_dir/config/certificates/$filename" ]; then
    if  echo $filename | grep crt ; then
      fancy_echo "creating cert $filename"
      cp  $DIR/install_files/bob.crt  $sami_dir/config/certificates/$filename
    else
      fancy_echo "creating key $filename"
      cp  $DIR/install_files/bob.key  $sami_dir/config/certificates/$filename
    fi
  fi
done < $DIR/install_files/certs
