#!/bin/sh
source helper_functions

if ! which rbenv; then
  fancy_echo "Installing rbenv version manager ..."
  brew install rbenv ruby-build
fi

append_to_bash_profile 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi'

if rbenv versions  | grep 2.4.3 -q > /dev/null; then
  fancy_echo "Ruby 2.4.3 is already installed..."
else 
  fancy_echo "Installing Ruby 2.4.3"
  RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 2.4.3
fi

if ! rbenv global | grep -q 2.4.3; then
  fancy_echo "Current Ruby version `ruby -v`"
  rbenv global 2.4.3
fi

if ! gem list | grep -q "rails (4.2.10)"; then
  export PATH="/usr/local/opt/libxml2/bin:$PATH"
  # Might need to add install for x-code tools here to prevent error 
  fancy_echo "Installing Rails 4.2.10"
  gem install rails -v 4.2.10
fi

if [ ! -d ~/.rbenv/plugins/rbenv-gem-rehash ]; then
  git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
  rbenv rehash
fi